### ISSUE TITLE
Bug: Not detecting sqlite3 install

### ISSUE THREAD

**Issue by benthecarman** [stakwork/sphinx-relay#107]
I am trying to run a sphinx-relay on a raspiblitz node.

I went through all the steps on [here](https://github.com/stakwork/sphinx-relay/blob/master/docs/raspiblitz_deployment.md) and am getting a weird error.

I get `Please install sqlite3 package manually` as an error, even though I already have it installed. I checked using `sqlite3 -version`.

Full error message:
```
bitcoin@raspberrypi:~/sphinx-relay/config $ npm run prod

> nodeapp@1.0.0 prod /home/bitcoin/sphinx-relay
> cp config/app.json dist/config/app.json && cp config/config.json dist/config/config.json && env NODE_ENV=production node dist/app.js

/home/bitcoin/sphinx-relay/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/home/bitcoin/sphinx-relay/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/home/bitcoin/sphinx-relay/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/home/bitcoin/sphinx-relay/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/home/bitcoin/sphinx-relay/node_modules/sequelize/lib/sequelize.js:324:20)
    at new Sequelize (/home/bitcoin/sphinx-relay/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.js:15:9)
    at Object.<anonymous> (/home/bitcoin/sphinx-relay/dist/src/models/index.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/bitcoin/sphinx-relay/dist/app.js:19:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodeapp@1.0.0 prod: `cp config/app.json dist/config/app.json && cp config/config.json dist/config/config.json && env NODE_ENV=production node dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeapp@1.0.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcoin/.npm/_logs/2020-11-20T06_12_50_757Z-debug.log

bitcoin@raspberrypi:~/sphinx-relay/config $ sqlite3 -version
3.27.2 2019-02-25 16:06:06 bd49a8271d650fa89e446b42e513b595a717b9212c91dd384aab871fc1d0alt1
```

**Comment by Evanfeenstra** [comment]
What node version do you have? We are running 12. If you are on 10 or lower definitely update

In our docker file we install sqlite3 twice in a row, and it solved this issue lol

**Comment by benthecarman** [comment]
```
bitcoin@raspberrypi:~ $ node -v
v14.15.1
```

> In our docker file we install sqlite3 twice in a row, and it solved this issue lol

I tried multiples times of uninstalling and re-installing sqlite3 which didn'twork

**Comment by benthecarman** [comment]
Found [this issue](https://github.com/sequelize/sequelize/issues/11174) and was able to resolve using

```
npm i sqlite3 -D && rm -rf node_modules && npm i && npm rebuild
```
