### ISSUE TITLE
Relay crashing with Cannot destructure property `channels` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by darrenahunter** [stakwork/sphinx-relay#12]
I have replay running on a mynode Rasp Pi4
it is now failing after receiving some contact msgs with the below

> nodeapp@1.0.0 prod /mnt/hdd/mynode/sphinx-relay
> cp config/app.json dist/config/app.json && cp config/config.json dist/config/config.json && env NODE_ENV=production node dist/app.js

=> env: production
=> [lnd] connecting... attempt #1
(node:14046) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
=> [db] starting setup...
=> [db] done syncing
=> [db] setup done
[socket] connected to server
Node listening on 3001.
=> [meme] authed!
=> received contact key {"type":10,"sender":{"pub_key":"03eab50cef61b9360bc24f0fd8a8cb3ebd7cec226d9f6fd39150594e0da8bd58a7","contact_key":"MIIBCgKCAQEAnxESUQpAoR5sliYX10fC6so1vW1ctR3QbYZZ27gwZEEakZtjsWLrng0zS2NCgZD1+odic1eqxj0dvoagqvhCDCMi413Tu32QMOdgG4sKSUaB3sGBttWyp9iTy8ZlCwbebGpHXRnjV0N+EL2VAooeKtJRJQj7YEWqY6Uh5535wUlptoxPWEBXOEJd7oH5vOzs5fYrEVHkpgUzmeScVRTHbA4IzRq31zhYZyp2wac4VAS1M9Qg1eCdntXwg5LxG7g4/QzTvwb1LGE1IvMeRbr8W6+4Lwtw5Huq0UCsp9vPXUfL4Dv6ktbIobadUkHrYGTkKyKqvyfIVravKDnYvhSsWwIDAQAB","alias":"Scott"}}
MESSAGE SENT outside SW! { payment_error: '',
  payment_preimage:
   <Buffer d0 83 48 65 b3 20 2f c5 d5 10 be 90 ce 09 38 1c 40 83 24 e4 ca ac c1 5c a2 ce 9d 0f eb 57 40 7f>,
  payment_route:
   { total_time_lock: 626867,
     total_fees: '1',
     total_amt: '2',
     hops: [ [Object], [Object], [Object] ],
     total_fees_msat: '1000',
     total_amt_msat: '2000' },
  payment_hash:
   <Buffer c5 ba 9b ac e2 45 3c 8a 93 6a 3b 0a 0e e9 8a b4 9c 64 63 56 8f 5c e3 ea 17 62 41 f9 0f 11 ff 11> }
=> received contact key {"type":10,"sender":{"pub_key":"03eab50cef61b9360bc24f0fd8a8cb3ebd7cec226d9f6fd39150594e0da8bd58a7","contact_key":"MIIBCgKCAQEAnxESUQpAoR5sliYX10fC6so1vW1ctR3QbYZZ27gwZEEakZtjsWLrng0zS2NCgZD1+odic1eqxj0dvoagqvhCDCMi413Tu32QMOdgG4sKSUaB3sGBttWyp9iTy8ZlCwbebGpHXRnjV0N+EL2VAooeKtJRJQj7YEWqY6Uh5535wUlptoxPWEBXOEJd7oH5vOzs5fYrEVHkpgUzmeScVRTHbA4IzRq31zhYZyp2wac4VAS1M9Qg1eCdntXwg5LxG7g4/QzTvwb1LGE1IvMeRbr8W6+4Lwtw5Huq0UCsp9vPXUfL4Dv6ktbIobadUkHrYGTkKyKqvyfIVravKDnYvhSsWwIDAQAB","alias":"Scott"}}
MESSAGE SENT outside SW! { payment_error: '',
  payment_preimage:
   <Buffer 37 30 7a 70 c0 70 b7 db 51 4f 85 14 9f bf e5 26 f4 b9 2e 3e 57 b4 f0 90 29 f9 ac ab ea a8 fa 69>,
  payment_route:
   { total_time_lock: 626867,
     total_fees: '1',
     total_amt: '2',
     hops: [ [Object], [Object], [Object] ],
     total_fees_msat: '1000',
     total_amt_msat: '2000' },
  payment_hash:
   <Buffer 77 6f ec 6d c9 46 67 c0 12 ec b6 e7 67 f2 de 6e 6d c6 58 bc 35 1f 72 61 18 6e 90 62 03 93 b8 7e> }
Status { code: 0,
  details: '',
  metadata: Metadata { _internal_repr: {}, flags: 0 } }
Closed stream
{ Error: 12 UNIMPLEMENTED: unknown service lnrpc.Lightning
    at Object.exports.createStatusError (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 12,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'unknown service lnrpc.Lightning' }
{ Error: 12 UNIMPLEMENTED: unknown service lnrpc.Lightning
    at Object.exports.createStatusError (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 12,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'unknown service lnrpc.Lightning' }
/mnt/hdd/mynode/sphinx-relay/dist/api/utils/nodeinfo.js:37
                const { channels } = channelList;
                        ^

TypeError: Cannot destructure property `channels` of 'undefined' or 'null'.
    at lightning.listChannels (/mnt/hdd/mynode/sphinx-relay/dist/api/utils/nodeinfo.js:37:38)
    at Object.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1210:9)
    at InterceptingListener._callNext (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodeapp@1.0.0 prod: `cp config/app.json dist/config/app.json && cp config/config.json dist/config/config.json && env NODE_ENV=production node dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeapp@1.0.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Evanfeenstra** [comment]
fixed in latest master
