### ISSUE TITLE
Relay crashes - Cannot destructure property `channels` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by darrenahunter** [stakwork/sphinx-relay#13]
a stightly different error as to one posted previously - but same channel destructure issue

> nodeapp@1.0.0 prod /mnt/hdd/mynode/sphinx-relay
> cp config/app.json dist/config/app.json && cp config/config.json dist/config/config.json && env NODE_ENV=production node dist/app.js

=> env: production
=> [lnd] connecting... attempt #1
(node:5047) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
=> [db] starting setup...
=> [db] done syncing
=> [db] setup done
[socket] connected to server
Node listening on 3001.
=> [meme] authed!
Status { code: 0,
  details: '',
  metadata: Metadata { _internal_repr: {}, flags: 0 } }
Closed stream
{ Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'failed to connect to all addresses' }
{ Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'failed to connect to all addresses' }
/mnt/hdd/mynode/sphinx-relay/dist/api/utils/nodeinfo.js:37
                const { channels } = channelList;
                        ^

TypeError: Cannot destructure property `channels` of 'undefined' or 'null'.
    at lightning.listChannels (/mnt/hdd/mynode/sphinx-relay/dist/api/utils/nodeinfo.js:37:38)
    at Object.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1210:9)
    at InterceptingListener._callNext (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodeapp@1.0.0 prod: `cp config/app.json dist/config/app.json && cp config/config.json dist/config/config.json && env NODE_ENV=production node dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeapp@1.0.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Evanfeenstra** [comment]
Do you have a channel open on your LND? What version is your LND running?

**Comment by darrenahunter** [comment]
Hi Evan
My LND version is "version": "0.9.2-beta commit=v0.9.2-beta"
And yes I have channel open - Paul opened one from Sphinx to my LN
I can DM you my getinfo and getnodeinfo if would help

**Comment by Evanfeenstra** [comment]
fixed in latest master
