### ISSUE TITLE
unknown service in lnrpc.Lightning - relay crashes

### ISSUE THREAD

**Issue by darrenahunter** [stakwork/sphinx-relay#19]
this is the terminal log of the crash

I wasn't messaging through the relay at the time - assuming it received this msg async

can't be sure how long after I started the relay but it had been running for a while

common timestamps on all log msgs would be handy

cheers

=> [meme] authed!
Status { code: 0,
  details: '',
  metadata: Metadata { _internal_repr: {}, flags: 0 } }
Closed stream
{ Error: 12 UNIMPLEMENTED: unknown service lnrpc.Lightning
    at Object.exports.createStatusError (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 12,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'unknown service lnrpc.Lightning' }
{ Error: 12 UNIMPLEMENTED: unknown service lnrpc.Lightning
    at Object.exports.createStatusError (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 12,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'unknown service lnrpc.Lightning' }
/mnt/hdd/mynode/sphinx-relay/dist/api/utils/nodeinfo.js:38
                    const { channels } = channelList;
                            ^

TypeError: Cannot destructure property `channels` of 'undefined' or 'null'.
    at lightning.listChannels (/mnt/hdd/mynode/sphinx-relay/dist/api/utils/nodeinfo.js:38:42)
    at Object.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1210:9)
    at InterceptingListener._callNext (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/mnt/hdd/mynode/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)

**Comment by Evanfeenstra** [comment]
Hi Darren, the latest version in master should fix this issue. Also it auto-reconnects if LND disconnects
