### ISSUE TITLE
sphinx relay container crashed while testing

### ISSUE THREAD

**Issue by antonilol** [stakwork/sphinx-relay#441]
log
```
[info] 09-29-22T07:37:04 [NETWORK] => received contact key from 02a38857848aca6b32ebcc3c85d07ee41354988f4f1e0b4e6ccd255eee6ed75b8d 1
/relay/dist/src/network/receive.js:333
        if (oldMember.lastAlias !== final_sender_alias) {
                      ^

TypeError: Cannot read properties of null (reading 'lastAlias')
    at /relay/dist/src/network/receive.js:333:23
    at Generator.next (<anonymous>)
    at fulfilled (/relay/dist/src/network/receive.js:5:58)
```

code
```ts
  const ww = { chatId: chat.id, contactId: senderContactId, tenant: owner.id }
  const oldMember = (await models.ChatMember.findOne({                             <-- findOne returned null
    where: ww,
  })) as ChatMember
  if (oldMember.lastAlias !== final_sender_alias) {                                <-- here it crashed
    await models.ChatMember.update(
      // this syntax is necessary when no unique ID on the Model
      { lastAlias: final_sender_alias },
      { where: ww }
    )
  }
```

**Comment by antonilol** [comment]
this crash happened when running controllers/tribe.test.ts on my amp branch and probably is the reason this test fails everywhere else now (like also #435 and it only changes a gh actions yml file)

**Comment by Evanfeenstra** [comment]
Thanks for pointing this out @antonilol !

**Comment by Evanfeenstra** [comment]
fixed here https://github.com/stakwork/sphinx-relay/commit/8c7c1daeb5fad80ee8dc07093827c34c0bbbbf00
