### ISSUE TITLE
error installing on myNode as per install_guide_myNode_and_Raspiblitz.md

### ISSUE THREAD

**Issue by dimaatmelodromru** [stakwork/sphinx-relay#61]
```
[tribes] try to connect: tls://tribes.sphinx.chat:8883
[db] created node owner contact, id: 1
[tribes] connected!
[tribes] updated stats for 0 tribes
=> [meme] authed!
[hub error] { FetchError: request to https://hub.sphinx.chat/api/v1/ping failed, reason: getaddrinfo EAI_AGAIN hub.sphinx.chat hub.sphinx.chat:443
    at ClientRequest.<anonymous> (/home/bitcoin/sphinx-relay/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  message:
   'request to https://hub.sphinx.chat/api/v1/ping failed, reason: getaddrinfo EAI_AGAIN hub.sphinx.chat hub.sphinx.chat:443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }
```

**Comment by kevkevinpal** [comment]
looks like when I post https://hub.sphinx.chat/api/v1/ping it works fine it may be a connectivity issue to that server nonetheless I don't think relay should crash if that ping fails

**Comment by kevkevinpal** [comment]
seems like we now have a hub warning after that ping call, I would try updating to the latest sphinx-relay version and try starting again. Closing
