### ISSUE TITLE
UNIMPLEMENTED: unknown service signrpc.Signer

### ISSUE THREAD

**Issue by Sjors** [stakwork/sphinx-relay#97]
I get this error when trying to join a tribe.

I can see my wallet balance, create an invoice and receive it, so must have gotten at least _something_ right in the installation :-)

On Ubuntu Linux with Lnd 0.11.1-beta, NodeJS v10.19.0.

```
[tribes] try to connect: tls://tribes.sphinx.chat:8883
[tribes] connected!
[tribes] updated stats for 0 tribes
=> random sig X660jCCOswy7ZAuWRHUWDegmCx_cpC8_lLqGgaGP5pzs2eLHrGsCHVVQPYcsXCkfwUBdpT8RlDO0zEzD5xafN5DGtc0E
=> starting subscription cron job 1: 44 15 * * 5
=> [meme] authed!
=> [socket.io] connected!
=> joinTribe
=> joinTribe: typeToSend 14
=> joinTribe: contactIdsToSend [1,4]
-> sending to  4 0236b79638b8f133eca00765786da784bd3db4187dd6e1f28be85d4a0f547150d8
(node:3885342) UnhandledPromiseRejectionWarning: Error: 12 UNIMPLEMENTED: unknown service signrpc.Signer
    at Object.exports.createStatusError (/home/lnd/src/sphinx-relay/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/lnd/src/sphinx-relay/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/lnd/src/sphinx-relay/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/lnd/src/sphinx-relay/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/lnd/src/sphinx-relay/node_modules/grpc/src/client_interceptors.js:847:24)
(node:3885342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3885342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried updating NodeJS to v14.15.0, deleting node_modules and `npm install` again, but to no avail.

**Comment by Evanfeenstra** [comment]
Hey, the "signrpc" is not included in your LND. Did you make from source? We recommend building all features into LND like this:

make install tags="autopilotrpc chainrpc invoicesrpc routerrpc signrpc walletrpc watchtowerrpc wtclientrpc"

**Comment by Sjors** [comment]
I indeed built Lnd from source. The `make install tags` part doesn't seem to help. Do I need to pass some addition info about it to `npm run prod`?

**Comment by Sjors** [comment]
Ah duh, I forgot to restart Lnd after that...
